# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
# warnings are  errors
warnings_are_errors: true

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
